### ISSUE TITLE
0.6.0 is breaking due to implicit sidekiq/api dependency

### ISSUE THREAD

**Issue by ivanreese** [adamlogic/rails_autoscale_agent#11]
It looks like the additional require in 967fa18ef74517dd8cce2ad6991b07ab822a1569 is to blame. I don't use sidekiq in my Rails app, so this require errors out.

I was previously using 0.4.1 without issue.

**Comment by adamlogic** [comment]
Thanks so much for reporting this. Now fixed in 0.6.1.
