### ISSUE TITLE
AutoscaleAgent is attempting to connect to Redis

### ISSUE THREAD

**Issue by jellybob** [adamlogic/rails_autoscale_agent#12]
I'm unable to set up the Autoscale agent in an application as I'm getting the following errors when it tries to report:

```
2019-11-26T12:32:46.236116+00:00 app[web.7]: E [RailsAutoscale] RailsAutoscaleAgent -- Reporter error: #<OpenSSL::SSL::SSLError: hostname "[REDACTED]" does not match the server certificate>
2019-11-26T12:32:46.369795+00:00 app[web.7]: E [RailsAutoscale] RailsAutoscaleAgent -- /app/vendor/ruby-2.5.5/lib/ruby/2.5.0/openssl/ssl.rb:394:in `post_connection_check'
```

The error is expected, as we've got Redis set up to forward through a proxy into Elasticache rather than using Heroku Redis, but what isn't clear to me is why its attempting to connect at all - I don't see any references to Redis in this repository.

**Comment by jellybob** [comment]
A bit more rummaging suggests this may be due to the Sidekiq adapter - we've got some config which tells Sidekiq to ignore certificate validation errors which needs to be loaded before attempted to interact with the Sidekiq API. Is there some way we could opt-out of Sidekiq monitoring?

**Comment by adamlogic** [comment]
Hey @jellybob, thanks for the additional info. Right now there's no way to opt out, but it should be an easy addition. I'll take a look!

**Comment by adamlogic** [comment]
@jellybob I just pushed a new version of the agent to master (not on Rubygems yet). You can now configure `worker_adapters` in an initializer. Can you verify that this works for you?

```ruby
# Gemfile
gem 'rails_autoscale_agent', github: 'adamlogic/rails_autoscale_agent', branch: 'master'

# config/initializers/rails_autoscale.rb
RailsAutoscaleAgent::Config.instance.worker_adapters = []
```

**Comment by jellybob** [comment]
Looks good to me, just shipped this version to the application in question and its happily sending queue time metrics. Thanks :)

**Comment by jellybob** [comment]
Now been in production for 7 days, and still working happily. Is there any chance you could cut a release so we can stop pulling the code in directly from Github?

**Comment by adamlogic** [comment]
Done! Thanks so much for your help on this.
