### ISSUE TITLE
Que support

### ISSUE THREAD

**Issue by morgoth** [adamlogic/rails_autoscale_agent#13]
There is a support already on a branch https://github.com/adamlogic/rails_autoscale_agent/compare/que

@adamlogic Any chances to get it into master and have it released in stable gem version?

**Comment by adamlogic** [comment]
@morgoth Thanks for the nudge! 😄 This is in master now.

Would you mind testing it out before I release a new gem? I did have another customer beta testing the branch, but I don't use Que myself, so I need somebody running it on master before I'm comfortable publishing it.

You would just need to change your Gemfile like so:

```ruby
gem 'rails_autoscale_agent', github: 'adamlogic/rails_autoscale_agent', branch: 'master'
```

After you deploy and enqueue some jobs, your app will be sending Que latency metrics to Rails Autoscale. You should then see the option to enable worker autoscaling in your Rails Autoscale settings (as shown in [this video](https://meet.google.com/?pli=1&authuser=1)).

If you run into any trouble, please email me (adam at railsautoscale.com). Thanks!!

**Comment by morgoth** [comment]
@adamlogic The version from master workes fine for us - we run it few days already with que workers.
You can release the new version of gem. Thanks.

**Comment by adamlogic** [comment]
@morgoth Thanks! Just released. 😄
