### ISSUE TITLE
[QUE] Incorrect behaviour when job fails

### ISSUE THREAD

**Issue by meceo** [adamlogic/rails_autoscale_agent#17]
In case a job fails the agent incorrectly considers that as a delay in a queue. In results, a queue gets scaled up to the limits.

**Comment by adamlogic** [comment]
Thanks @meceo! I'll get a fix out today.

**Comment by adamlogic** [comment]
@meceo I have a fix for this in a branch. Are you able to see if this fixes the issue?

```
gem 'rails_autoscale_agent', github: 'adamlogic/rails_autoscale_agent', branch: 'que-ignore-retries'
```
