### ISSUE TITLE
Rails server fails immediately after gem is added

### ISSUE THREAD

**Issue by jimmyasyraf** [adamlogic/rails_autoscale_agent#19]
According to the docs, 

#### The middleware does nothing if `RAILS_AUTOSCALE_URL` is not present, such as in development or a staging app.

However, after adding the gem and bundle install and nothing else, starting rails server fails immediately. Is there something I'm missing? This is local development. We intend to use `rails_autoscale_agent` once deployed in Heroku

```
.gem/ruby/2.7.0/gems/rails_autoscale_agent-0.8.0/lib/rails_autoscale_agent/railtie.rb:11:in `block in <class:Railtie>'
.gem/ruby/2.7.0/gems/rails_autoscale_agent-0.8.0/lib/rails_autoscale_agent/logger.rb:18:in `block (2 levels) in <class:LoggerProxy>'
.rubies/ruby-2.7.0/lib/ruby/2.7.0/logger.rb:528:in `info'
.gem/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/logger_thread_safe_level.rb:53:in `add'
.rubies/ruby-2.7.0/lib/ruby/2.7.0/logger.rb:475:in `add'
.rubies/ruby-2.7.0/lib/ruby/2.7.0/logger.rb:585:in `format_message'
undefined method `bold' for "∙ ":String (NoMethodError)
```

**Comment by adamlogic** [comment]
@jimmyasyraf I'm sorry this issue somehow slipped by me.

That is a really odd error you encountered. It failed on [this line](https://github.com/adamlogic/rails_autoscale_agent/blob/master/lib/rails_autoscale_agent/railtie.rb#L11) and somehow ended up raising `undefined method 'bold' for "∙ ":String (NoMethodError)`.

I'm just completely baffled. 😕 

Are you still blocked on using this?

**Comment by jimmyasyraf** [comment]
@adamlogic we're not using rails autoscale at the moment so it's not blocking. We may in the future
