### ISSUE TITLE
Move to log statement to debug log level

### ISSUE THREAD

**Issue by tylerjolmstead** [adamlogic/rails_autoscale_agent#26]
The below line logs each time measurements are reported. This makes the gem very chatty in production, with low value in my opinion. Would you accept a pull request that changed this line to debug log level?

https://github.com/adamlogic/rails_autoscale_agent/blob/4002fc9ec8b655d4eb2e7e0967762fc792ba54e2/lib/rails_autoscale_agent/reporter.rb#L58

**Comment by adamlogic** [comment]
Yes, I think that makes sense.

**Comment by adamlogic** [comment]
@tylerjolmstead I decided to leave the reporter logging as INFO, but I did add the ability to silence INFO logs in 4897719.
