### ISSUE TITLE
Scale down happens, even when the worker is working on job(s)

### ISSUE THREAD

**Issue by mobilutz** [adamlogic/rails_autoscale_agent#27]
I stumbled over something in our staging environment, that normally does not happen on any of our LIVE instances.

Situation:
* worker is working on one job for `> scaledown timeframe` (i.e. 180 seconds)
* no additional jobs in the queue

Outcome:
* worker is being scaled down automatically

This is of course not an ideal situation, and maybe a very rare edge case, but it should be something that the addon should handle.

When I do find some time, I will look into this a bit more, and create an example setup, but I guess the situation is not hard to reproduce.

**Comment by adamlogic** [comment]
@mobilutz Thanks for reporting this. I've added some [support docs](https://railsautoscale.com/docs/questions/#why-are-my-long-running-jobs-being-terminated-when-scaling-down) about it, but I agree long-running jobs need a real solution.

**Comment by adamlogic** [comment]
@mobilutz Do you still have an issue with long-running jobs being terminated?

I have a solution that's working well, and I'm currently beta testing with a few customers. Email me (Adam at Rails Autoscale) if you're interested!
