### ISSUE TITLE
Add little doc for Rack/Sinatra apps

### ISSUE THREAD

**Issue by troex** [adamlogic/rails_autoscale_agent#29]
I have to add these lines to my Sinatra app:

```
require 'rails_autoscale_agent/middleware'
use RailsAutoscaleAgent::Middleware
```

`require 'rails_autoscale_agent'` - didn't work because it only loads `middleware` if there is a Railtie in the app, which is missing in Sinatra/Rack app.

**Comment by troex** [comment]
one more little note - `require 'rails_autoscale_agent/logger'`is loaded from `railtie` which doesn't trigger when just `middleware` included.

But `require 'rails_autoscale_agent/logger'` also present in `reporter` which is loaded by `middleware` - it looks that loading sequence could be improved a bit

**Comment by adamlogic** [comment]
@troex Thanks for the report! There is [this bit of the README](https://github.com/adamlogic/rails_autoscale_agent#non-rails-rack-apps) that addresses other (non-Rails) Rack apps.

Regarding how `logger` is required... It's being required in every file it's used. `require` is essentially a no-op if it's already been required. Perhaps I'm missing something?

**Comment by troex** [comment]
@adamlogic right but using `use RailsAutoscaleAgent::Middleware` without prior `require 'rails_autoscale_agent/middleware'` will fail to start the app, it will even fail with `require 'rails_autoscale_agent'`

what about the logger I guess is just about the style so doesn't really affect

**Comment by adamlogic** [comment]
Good point! I've updated the README. Thanks!
