### ISSUE TITLE
Change of heroku app name is not reflected in RailsAutoscale

### ISSUE THREAD

**Issue by mobilutz** [adamlogic/rails_autoscale_agent#30]
While setting up an application for my company, I added the AutoScale Addon, and then needed to change the name of the application in heroku.

Now I have a difference between RailsAutoScale URLs and heroku app urls.

This is for sure an edge situation, but it can happen and might lead to problems for a novice user, when he needs to change things.

And this case is very special:
1. setup 2 heroku applications (`app-1` and `app-2` with RailsAutoscale
1. on heroku rename `app-1` into `app-2a`
1. on heroku rename `app-2` into `app-1`
1. on heroku rename `app-2a` into `app-2`
1. **OUTCOME** URLs on heroku and autoscale are "inverted"

**Comment by adamlogic** [comment]
@mobilutz Thanks for reporting this. Should be a relatively quick fix to keep the app name in sync. I'll follow up here when that fix is in place.

**Comment by adamlogic** [comment]
Hey @mobilutz, just FYI that app names are now kept in sync. LMK if you're seeing otherwise. 👍

**Comment by mobilutz** [comment]
Thanks @adamlogic 
👍🏻 Now the name on rails-autoscale is the same as on heroku! So you guys use the name from heroku correctly now even when changing it!
