### ISSUE TITLE
UI issue - width of threshold could be wider

### ISSUE THREAD

**Issue by mobilutz** [adamlogic/rails_autoscale_agent#31]
This is not really an "issue" with the `rails_autoscale_agent` and very minor as well.

We have one worker, which we do not need to scale too quickly, therefore our upscale threshold is 100_000 seconds. And this is not easily visible in the Settings page UI:
![Screenshot 2020-09-28 at 08 27 05](https://user-images.githubusercontent.com/491877/94397791-bcc02b00-0164-11eb-9d02-6b07012b3341.png)

Looking through the HTML, I found the attribute `size="4"` on the input, when this is for example changed to `size="7"` the number fits (but needs a `text-align="right"` for smaller numbers I think):
![Screenshot 2020-09-28 at 08 27 14](https://user-images.githubusercontent.com/491877/94397881-d2cdeb80-0164-11eb-8212-c2d2033e9a9f.png)

Maybe this is something that can be changed in the Settings UI.

**Comment by adamlogic** [comment]
@mobilutz Done. Thanks for the suggestion!

**Comment by mobilutz** [comment]
Thanks for the fast change!
