### ISSUE TITLE
queue_time > 2G

### ISSUE THREAD

**Issue by fxtentacle** [adamlogic/rails_autoscale_agent#33]
Not sure how that happened, but when I had
```
proxy_set_header X-Request-Start "t=${msec}";
```
in my nginx conf on Heroku, then 
https://github.com/adamlogic/rails_autoscale_agent/blob/master/lib/rails_autoscale_agent/request.rb#L37
turned out extremely large, like 2147483648ms

I saw the error on heroku-18 with Ruby 2.6.5. And as expected, removing the proxy_set_header command from nginx fixed it. But the documentation for Rails Autoscale should probably mention that this header is important.

In case you're wondering why someone would set that header manually ... New Relic is recommending to do that:
https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples

**Comment by adamlogic** [comment]
Sorry you ran into this @fxtentacle! I'd added handing for the nginx header in https://github.com/adamlogic/rails_autoscale_agent/commit/5fbc41ad6d0d68fc382d75584795a85a35ad748f and https://github.com/adamlogic/rails_autoscale_agent/commit/cd092f38718abf5ffaea866bcae7831d4c910ffd, but those fixes are only in master.

I'm planning to cut a release in the next couple weeks. Thanks for reporting!
