### ISSUE TITLE
0.9.2 Release

### ISSUE THREAD

**Issue by dyakovlev** [adamlogic/rails_autoscale_agent#34]
It looks like there's been a number of fixes merged since 0.9.1, which was in late July. Would it be possible to release a new version? 

We're currently installing this gem via an explicit git sha to get a specific fix. This works fine, but has some dependency management burden. 

Thank you!

**Comment by adamlogic** [comment]
@dyakovlev Sorry for the delay on this release! I have some larger changes in master that I'm not comfortable putting in a patch release. I'm hoping to release 0.10.0 this month.

**Comment by dyakovlev** [comment]
Thanks!
