### ISSUE TITLE
Memory leak in store.rb

### ISSUE THREAD

**Issue by troex** [adamlogic/rails_autoscale_agent#39]
Hi, we recently started migrating to fully async with https://socketry.github.io/falcon/ server, replacing all IO operations with async methods and it looks like `rails_autoscale_agent` gem is leaking memory.

In https://github.com/adamlogic/rails_autoscale_agent/blob/v0.10.2/lib/rails_autoscale_agent/store.rb you are using Singelton for store class but that doesn't make your code thread-safe or fiber-safe I think. I suggest the problem is in the way you access `@measurements` I think you need Mutex around it. I'm not expert in fiber/async field I hope @ioquatix can give you insights why this code could be unsafe under falcon/async.

You can see on the graph that memory became stable after last push - where I have removed `rails_autoscale_agent`.
<img width="972" alt="Metrics | Heroku 2021-07-12 13-24-39" src="https://user-images.githubusercontent.com/436912/125272648-c2ae8380-e314-11eb-8297-f556fc7bd29c.png">

Below is Ruby heap dump (https://github.com/schneems/heapy gem formatter) after couple of hours of running web instance.

```
$ bundle exec heapy read ~/Downloads/ruby-heap-1626046021.dump all --lines=10

Analyzing Heap (Generation: all)
-------------------------------

allocated by memory (24619435) (in bytes)
==============================
  4976035  /app/vendor/bundle/ruby/3.0.0/gems/async-io-1.32.1/lib/async/io/stream.rb:136
  4522866  /app/vendor/bundle/ruby/3.0.0/gems/rails_autoscale_agent-0.10.2/lib/rails_autoscale_agent/store.rb:18
  3789256  /app/vendor/bundle/ruby/3.0.0/gems/rails_autoscale_agent-0.10.2/lib/rails_autoscale_agent/store.rb:23
  1640000  /app/vendor/bundle/ruby/3.0.0/gems/rollbar-3.2.0/lib/rollbar/util.rb:49
  1051618  eval:6
   865760  /app/vendor/ruby-3.0.1/lib/ruby/3.0.0/socket.rb:593
   482240  /app/vendor/bundle/ruby/3.0.0/gems/falcon-0.39.1/lib/falcon/adapters/rack.rb:143
   460200  /app/vendor/bundle/ruby/3.0.0/gems/protocol-http1-0.14.1/lib/protocol/http1/connection.rb:224
   455856  /app/vendor/bundle/ruby/3.0.0/gems/async-1.29.1/lib/async/task.rb:256
   290048  <internal:kernel>:49

object count (212926)
==============================
  52629  /app/vendor/bundle/ruby/3.0.0/gems/rails_autoscale_agent-0.10.2/lib/rails_autoscale_agent/store.rb:23
  52592  /app/vendor/bundle/ruby/3.0.0/gems/rails_autoscale_agent-0.10.2/lib/rails_autoscale_agent/store.rb:18
  11505  /app/vendor/bundle/ruby/3.0.0/gems/protocol-http1-0.14.1/lib/protocol/http1/connection.rb:224
   9210  /app/vendor/bundle/ruby/3.0.0/gems/rollbar-3.2.0/lib/rollbar/util.rb:49
   5444  /app/vendor/bundle/ruby/3.0.0/gems/protocol-http-0.22.4/lib/protocol/http/header/split.rb:31
   3502  /app/vendor/bundle/ruby/3.0.0/gems/rollbar-3.2.0/lib/rollbar/util.rb:72
   3490  /app/vendor/bundle/ruby/3.0.0/gems/protocol-http-0.22.4/lib/protocol/http/headers.rb:284
   3102  /app/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/cache.rb:841
   2859  /app/vendor/bundle/ruby/3.0.0/gems/protocol-http-0.22.4/lib/protocol/http/headers.rb:257
   2715  /app/vendor/bundle/ruby/3.0.0/gems/async-io-1.32.1/lib/async/io/generic.rb:216

High Ref Counts
==============================

  52628  /app/vendor/bundle/ruby/3.0.0/gems/rails_autoscale_agent-0.10.2/lib/rails_autoscale_agent/store.rb:23
  52591  /app/vendor/bundle/ruby/3.0.0/gems/rails_autoscale_agent-0.10.2/lib/rails_autoscale_agent/store.rb:18
  21098  /app/vendor/bundle/ruby/3.0.0/gems/falcon-0.39.1/lib/falcon/adapters/rack.rb:143
   9518  <internal:kernel>:49
   8201  /app/vendor/bundle/ruby/3.0.0/gems/protocol-http1-0.14.1/lib/protocol/http1/connection.rb:224
   7736  /app/vendor/bundle/ruby/3.0.0/gems/protocol-http-0.22.4/lib/protocol/http/headers.rb:298
   6723  /app/vendor/bundle/ruby/3.0.0/gems/protocol-http-0.22.4/lib/protocol/http/headers.rb:256
   6658  /app/vendor/bundle/ruby/3.0.0/gems/async-1.29.1/lib/async/task.rb:256
   3972  /app/vendor/bundle/ruby/3.0.0/gems/rollbar-3.2.0/lib/rollbar/util.rb:49
   3792  /app/vendor/bundle/ruby/3.0.0/gems/protocol-http-0.22.4/lib/protocol/http/headers.rb:284
```

We didn't have such issue while running `puma` even under higher load.

Also what is weird to me that it's staging environment and we don't have rails autoscale setup there at all, just the gem loads with middleware but we don't have ENV variables set at all so I suggest if should not instrument such instance at all

```
I, [2021-07-12T13:45:39.488512 #5165]  INFO -- : [RailsAutoscale] Sidekiq enabled
I, [2021-07-12T13:45:39.491959 #5165]  INFO -- : [RailsAutoscale] Reporter not started: RAILS_AUTOSCALE_URL is not set
```

PS maybe another improvement - I don't think `Sidekiq enabled` should be happening if I'm not running sidekiq server, it's just web instance it's only sidekiq client which pushes jobs, not really running jobs, so I don't want to slowdown web instances instrumenting background jobs.

**Comment by ioquatix** [comment]
Great, thanks for investigating this, well debugging this kind of code is my area, so I'll take a look.

**Comment by ioquatix** [comment]
It looks like `@measurements` is growing unbounded.

It looks like we should add:

```
    def initialize
      @measurements = []
      @last_pop = Time.now
    end
 ```

Also there is no mutex to guard this, so `#push` and ` #pop_report` appear to be thread unsafe.

**Comment by adamlogic** [comment]
Thanks for reporting this! I will take a look.

**Comment by adamlogic** [comment]
@ioquatix You're totally right that `@measurements` is growing unbounded. I had added [this line](https://github.com/adamlogic/rails_autoscale_agent/blob/4befcf59f01b54c7f6dc76139867de236f348b2e/lib/rails_autoscale_agent/store.rb#L21) to prevent that from happening, but as you point out I never initialized `@last_pop`. 🤦‍♂️ 

> Also what is weird to me that it's staging environment and we don't have rails autoscale setup there at all

@troex This is exactly the scenario that causes `@measurements` to grow unbounded, because the measurements are never reported. I don't think the symptoms you're seeing have anything to do with Falcon or thread-safety.

I don't want to be dismissive of thread-safety issues, though. It's true that multiple threads will access the same singleton instance, and it's also true that I'm not wrapping any of the instance variable access in a mutex. But since the `@measurements` operations are atomic (`shift` and `<<`), I didn't think I had a thread-safety concern.

Perhaps I'm wrong about that, though.

> PS maybe another improvement - I don't think Sidekiq enabled should be happening if I'm not running sidekiq server, it's just web instance it's only sidekiq client which pushes jobs, not really running jobs, so I don't want to slowdown web instances instrumenting background jobs.

Run this to turn off all worker metrics:

```
heroku config:add RAILS_AUTOSCALE_WORKER_ADAPTER=""
```

More info [here](https://github.com/adamlogic/rails_autoscale_agent/blob/master/README.md#worker-adapters), but LMK if you think something's missing.

**Comment by ioquatix** [comment]
> But since the @measurements operations are atomic (shift and <<), I didn't think I had a thread-safety concern.

They are not guaranteed to be atomic.

- Non-CRuby implementations.
- User overrides `Array#<<` with pure Ruby implementation.

**Comment by adamlogic** [comment]
Yeah, that's fair.
