### ISSUE TITLE
Verify Heroku Dyno Type from Rails Autoscaled Instances

### ISSUE THREAD

**Issue by berniechiu** [adamlogic/rails_autoscale_agent#45]
Hi Adam,

Thanks for the nice tool. We're wondering if it's possible to know which `$DYNO_TYPE` is from autoscaled instances, so we could disable something like DataDogs metrics and lower the costs on those scaled out dynos.

This is something we have in the `prerun.sh` built-in from DataDog supporting some Heroku environments:

REF: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#prerun-script
```bash
if [ "$DYNOTYPE" == "run" ] || [ "$DYNOTYPE" == "scheduler" ] || [ "$DYNOTYPE" == "release" ]; then
  DISABLE_DATADOG_AGENT="true"
fi
```

**Comment by adamlogic** [comment]
I'm not sure I completely understand the question, but Heroku numbers the dynos sequentially for each process. For example, you will *always* have a `web.1` dyno, and as you scale out (manually or via autoscaling) that number increases.

You could extract that number from `$DYNO` similar to how [DataDog's buildpack extracts `DYNOTYPE`](https://github.com/DataDog/heroku-buildpack-datadog/blob/18fc145e2bbde510fd6a48e94c9a8281239ab790/extra/datadog.sh#L66) and use the value to decide whether to disable metrics.

Does that help?

**Comment by berniechiu** [comment]
sounds good! Thanks
