### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by jekuno** [adamlogic/rails_autoscale_agent#7]
Could you please add some details to the README.md which data are being sent to `RAILS_AUTOSCALE_URL`(https://railsautoscale.com/api/...) when installing the gem and how these data are processed or stored?

**Comment by adamlogic** [comment]
Absolutely! I should get to this in the next few days. In the meantime, check out the [`Reporter` spec](https://github.com/adamlogic/rails_autoscale_agent/blob/master/spec/reporter_spec.rb) for an example of the data that's sent to Rails Autoscale.

**Comment by jekuno** [comment]
All right. Thanks.

**Comment by adamlogic** [comment]
Hey @jekuno, I [updated the README](https://github.com/adamlogic/rails_autoscale_agent/blob/master/README.md#what-data-is-collected) with details about what data is being collected. LMK if you have any other questions/concerns about it.
