### ISSUE TITLE
Consider removing activesupport dependency?

### ISSUE THREAD

**Issue by timriley** [adamlogic/rails_autoscale_agent#8]
Hi @adamlogic — we're evaluating Rails Autoscale on some apps of ours, but bringing in the agent means we bring in activesupport as a transitive dependency, and we'd rather avoid having it in our Gemfile.lock altogether.

Would you consider a PR that removes the activesupport dependency? As far as I can tell, it's only there so you can depend on having a logger with tagging? It seems you've done some work to account for non-activesupport loggers in master already, which I'd like to extend a little, probably along these lines:

1. Remove activesupport from the gemspec and put it in the Gemfile instead (so you can use it in your tests)
2. Instead of extending the provided logger instance with `FakeTaggedLogging` (which feels pretty intrusive), I'd set up a logger class that wraps the provided logger, and then uses `respond_to?` to determine whether to emit tagged log messages or simple plain (untagged) ones

I feel by removing this dependency, the agent would be more palatable to a wider range of Ruby developers, especially those working outside of the Rails ecosystem.

Either way, I thought I'd flag this with you first before getting to work, since you may have a perspective on this I haven't considered yet :)

Looking forward to your feedback! Thanks!

**Comment by adamlogic** [comment]
100% in favor of this!

**Comment by timriley** [comment]
Thanks for closing the loop on this, Adam 🙏🏼

Sorry I never got to it myself!
