### ISSUE TITLE
Please release current master as a new version

### ISSUE THREAD

**Issue by juno** [adamlogic/rails_autoscale_agent#9]
Hi, Adam.

First, thank you for this add-on.
I evaluated this and subscribed last week, so far I'm happy with it. 👍 

Today, I noticed that our log bloated with these lines from dyno:
```
INFO -- : [RailsAutoscale] Collected queue_time=4ms request_id=6db5645d-2d58-47cf-a5ad-0a51fdf8bc1d request_size=0
```

It seems that you had change (a8074cd2d4d9bff48a5fc42ed7da654c0982e586) log level of this line to debug from info, however latest release (`0.4.0`) doesn't contains the fix.

Could you release a new version?

**Comment by adamlogic** [comment]
👍 Done!
